describe EmModbusHandler do
	it 'should fail fast when the server is not running'
	it 'should be able to read an array of words'
	it 'should be able to write an array of words'
	it 'should return an error if asking for address outside physical memory'
	it 'should be able to read an array of coils'
	it 'should be able to write an array of coils'
	it 'should be able to write to single bits in a word'
	it 'should support different values for unit identifier'
	it 'should increment the transaction identifier between requests'
	it 'should reset the transaction identifier on overflow'
	it 'should raise exceptions when too many words/coild are used'
	it 'should accept the slave address option'
	it 'should accept the max size override options'
end
